services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    entrypoint: ["bash", "-c", "docker-entrypoint.sh postgres & sleep 5 && psql -U ${DB_USER} -d postgres -c 'CREATE DATABASE test_db;' && psql -U ${DB_USER} -d postgres -c 'CREATE DATABASE dictionary;' && wait"]

volumes:
  pgdata:
