// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnglishWord struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type Example struct {
	ExampleID string `json:"exampleId"`
	Text      string `json:"text"`
}

type Mutation struct {
}

type PolishWord struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type Query struct {
}

type Translation struct {
	PolishWord  *PolishWord  `json:"polishWord"`
	EnglishWord *EnglishWord `json:"englishWord"`
	Examples    []*Example   `json:"examples"`
}

type TranslationInput struct {
	PolishWord  string   `json:"polishWord"`
	EnglishWord string   `json:"englishWord"`
	Examples    []string `json:"examples"`
}
